Remove use of ENUMs in logic
SAP/abap-file-formats-tools pull request #159
Opened 2022-08-03 13:48 UTC by larshp

2022-08-03 15:59 UTC, schneidermic0 commented
> This PR removes use of ENUMS, as they are currently used for the purpose of their contents.

Maybe, I don't get the reason for this PR. Why do you think they are used for the purpose of their contents? Except of the first, the don't even specify values:

```
  TYPES:
     BEGIN OF ENUM enum_formatting_option STRUCTURE formatting_option,
       no_formatting VALUE IS INITIAL,
       camel_case    VALUE 1,
     END OF ENUM enum_formatting_option STRUCTURE formatting_option.

   TYPES:
     BEGIN OF ENUM enum_type_info STRUCTURE type_info,
       string,
       numeric,
       boolean,
       date_time,
     END OF ENUM enum_type_info STRUCTURE type_info.

   TYPES:
     BEGIN OF ENUM enum_operation STRUCTURE operation,
       initial,
       write_element,
       open_structure,
       close_structure,
       open_table,
       close_table,
     END OF ENUM enum_operation STRUCTURE operation.
```

2022-08-03 17:15 UTC, larshp commented
A: The unit test in https://github.com/SAP/abap-file-formats-tools/blob/cd44700a9924cc80c317067bf24c45bb44d21af4/src/zcl_aff_writer.clas.testclasses.abap#L236 relies on "initial" the first ENUM to be initial.

There is no assignment of the "initial" ENUM anywhere, so I'd guess it is never used.

However, INITIAL handing is strange in ENUMS, at best misleading, guess the output of this code,

```abap
TYPES:
  BEGIN OF ENUM enum_formatting_option STRUCTURE formatting_option,
    no_formatting VALUE IS INITIAL,
    camel_case    VALUE 1,
  END OF ENUM enum_formatting_option STRUCTURE formatting_option.
ASSERT formatting_option-no_formatting IS INITIAL.
WRITE formatting_option-no_formatting.
```

B: method [get_json_schema_type()](https://github.com/SAP/abap-file-formats-tools/blob/4490c25515d6ea5cfbd0c37af5c52a8503be401a/src/zcl_aff_writer_json_schema.clas.abap#L634) takes an ENUM as input in `json_type`, this enum is(depending on its value) `result = to_lower( type ).` which is the json output.

I.e. renaming the ENUMs will change the generated schema, ie. ENUMS are used for the purpose of their contents

2022-08-05 12:44 UTC, schneidermic0 commented
@wurzka and I had a look at this PR, again.

We think we have to distinguish between following aspects

A) code in abap-file-formats-tools shall not use enums so that it will be easier to using the transpiler for running unit tests in GitHub.

B) abap-file-formats-tools infrastructure does not support processing enums.

@larshp If we get you right, your goal is A only, isn't it? I.e., abap-file-formats-tools shall still be able to process enums.

We would agree to A if this enabled us to run more unit tests.

2022-08-05 12:45 UTC, schneidermic0 requested changes
> Note: I have not run the unit tests on a real system, cl_oo_abap_doc_reader does not exist on any system I have access to

We ran the tests in our system. There are a bunch of unit test errors.

2022-08-05 12:45 UTC, larshp commented
yes, only "A"

2022-08-05 12:46 UTC, schneidermic0 commented
I suggest, we try to remove the unit test errors.

2022-08-05 12:50 UTC, schneidermic0 requested changes
See my comment + failing tests need to be fixed.

2022-08-05 12:50 UTC, schneidermic0 commented on src/zcl_aff_writer.clas.testclasses.abap
> +    cl_abap_unit_assert=>assert_equals( exp = zif_aff_writer=>type_info-string act = cut->get_json_type_from_description( get_element_description( '' ) ) ).
> yes, only "A"

In this case, we should revert this particular change. As far as I understand, this test shall verify, that the framework considers enums as `"type": "string"` in the JSON-schema.

Most probably, we have to define a local enum in the test and pass it to the method.

2022-08-05 15:06 UTC, schneidermic0 commented on src/zcl_aff_writer.clas.testclasses.abap
> +    cl_abap_unit_assert=>assert_equals( exp = zif_aff_writer=>type_info-string act = cut->get_json_type_from_description( get_element_description( '' ) ) ).
Added my suggestion with https://github.com/SAP/abap-file-formats-tools/pull/159/commits/045a1e88b1623dc10b70d54e08ca801fd6757a72

2022-08-05 15:16 UTC, schneidermic0 commented
abaplint errors are valid. However, I need the enum just for test reasons here. Can we add an exception somehow without changing the rule?

2022-08-05 15:48 UTC, larshp commented
yup, skipped with https://github.com/SAP/abap-file-formats-tools/pull/159/commits/8bb5a573cfd7785ecc171cd7987eb300567b503d

2022-08-06 15:53 UTC, schneidermic0 approved these changes
Unit tests are green, now.

2022-08-08 06:28 UTC, wurzka approved these changes
LGTM

2022-08-08 06:40 UTC, merged