Add annotation for content encoding/media type
SAP/abap-file-formats-tools pull request #231
Opened 2023-03-17 20:15 UTC by huber-nicolas

2023-03-17 20:28 UTC, huber-nicolas commented
I think the remaining abaplint findings are no valid findings

2023-03-19 07:52 UTC, larshp commented
unit test will be fixed with https://github.com/SAP/abap-file-formats-tools/pull/229

2023-03-20 08:54 UTC, wurzka requested changes
Functionally, it looks good to me.

See my comments about the code

2023-03-20 08:54 UTC, wurzka commented on src/zcl_aff_writer_json_schema.clas.abap
> +    IF abap_doc-content_media_type IS NOT INITIAL.
Same as above

2023-03-20 08:54 UTC, wurzka commented on src/zcl_aff_writer_json_schema.clas.testclasses.abap
> +    content_encoded_integer FOR TESTING RAISING cx_static_check,
Indentation

2023-03-20 11:34 UTC, larshp commented
overall, what is this feature related to? 

I've been arguing to collect the JSON data in few files, but I'd not expect to encode other filetypes inside the JSON as the examples in https://json-schema.org/understanding-json-schema/reference/non_json_data.html#id4

If there is a html or png file, just encode it as another file as per https://github.com/SAP/abap-file-formats/blob/main/docs/specification.md#file-names ?

2023-03-20 12:05 UTC, larshp commented
does the unit test pass in a real system?

2023-03-20 12:49 UTC, schneidermic0 commented
> as in openapi REST? see https://github.com/abap-openapi/

I am not sure what you mean.

2023-03-21 10:35 UTC, wurzka commented on src/zif_aff_log.intf.abap
>      co_msg129 TYPE string VALUE `Fields of a different type than integer should not use the annototation $multipleOf` ##NO_TEXT.
Maybe we should keep the correct order

2023-03-21 13:15 UTC, wurzka approved these changes
LGTM :)

2023-03-21 13:16 UTC, wurzka commented
@larshp Failing unit test is green in our system. We do not know why it is failing here

2023-03-23 15:11 UTC, huber-nicolas commented on test/abap_transpile.json
> +      {"object": "ZCL_AFF_ABAP_DOC_PARSER", "class": "ltcl_aff_abap_doc_parser", "method": "content_media_multiple_entries"},
```suggestion
      {"object": "ZCL_AFF_ABAP_DOC_PARSER", "class": "ltcl_aff_abap_doc_parser", "method": "content_media_multiple_entries"},
      {"object": "ZCL_AFF_ABAP_DOC_PARSER", "class": "ltcl_aff_abap_doc_parser", "method": "content_encod_multiple_entries"},
```

2023-03-23 15:13 UTC, merged