Documentation for content media type and content encoding
SAP/abap-file-formats-tools pull request #234
Opened 2023-03-24 15:29 UTC by wurzka

With #231, we added annotations for content media type and content encoding.
This pull request adds the corresponding documentation.

2023-03-24 15:31 UTC, larshp commented
but well, this is not a feature for ABAP file formats, right?

2023-03-24 15:33 UTC, wurzka commented
Yes, this should not be used for AFF. Hence, we wanted to document it here instead of the AFF-repo

2023-03-24 15:41 UTC, schneidermic0 commented on README.md
> +## Usage
```suggestion
## How To Use
```

2023-03-24 15:42 UTC, schneidermic0 commented on README.md
> +Additionally to the AFF-related annotation, one can also use the following:
```suggestion
Additionally to the ABAP-file-formats-related annotations, one can also use the following:
```

2023-03-24 15:43 UTC, schneidermic0 commented on README.md
> + ### Content Encoding
I think we should remove the space in the beginning:

```suggestion
### Content Encoding
```

2023-03-24 15:47 UTC, schneidermic0 commented
> but well, this is not a feature for ABAP file formats, right?

Any suggestions where we should document the behavior of the generator? As @wurzka wrote. Since it is not a feature of AFF, we moved the documentation to this repository.

2023-03-24 15:55 UTC, larshp commented
I think the content-type feature would typically be needed in a REST setup, which is already covered else-ware

I suggest keeping the feature list as small as possible, as it will keep everything working

2023-03-24 16:15 UTC, schneidermic0 commented
> I suggest keeping the feature list as small as possible, as it will keep everything working

We wouldn't add if it was not needed. ;) It's really about transferring non-JSON data within a JSON document. See also https://json-schema.org/understanding-json-schema/reference/non_json_data.html

As mentioned before it is not related to the ABAP-file-formats. However, forking the tooling just for this use case seem also a bit over-engineered, isn't it?

2023-03-24 16:32 UTC, larshp commented
true

but if you choose to share the use-case, then it will be possible to share alternative solutions

2023-03-24 16:44 UTC, schneidermic0 commented
> but if you choose to share the use-case, then it will be possible to share alternative solutions

I need to check whether I can already share it.

2023-03-27 07:08 UTC, albertmink requested changes
Spell checker suggestions

2023-03-27 07:08 UTC, albertmink commented on README.md
> +## How To Use
```suggestion
## How to Use
```

2023-03-27 07:08 UTC, albertmink commented on README.md
> +* `z_generate_repo` generates files and folder hierarchy for upload and maintain the [abap-file-formats](https://github.com/SAP/abap-file-formats) repository (requires ABAP file format framework)
```suggestion
* `z_generate_repo` generates files and folder hierarchy for uploading and maintaining the [abap-file-formats](https://github.com/SAP/abap-file-formats) repository (requires ABAP file format framework)
```

2023-03-27 07:08 UTC, albertmink commented on README.md
> +Different possibilities on adding more information via annotations are listed [here](https://github.com/SAP/abap-file-formats/blob/main/docs/json.md#writing-JSON-schema-with-ABAP-types).
```suggestion
Different possibilities for adding more information via annotations are listed [here](https://github.com/SAP/abap-file-formats/blob/main/docs/json.md#writing-JSON-schema-with-ABAP-types).
```

2023-03-27 07:08 UTC, albertmink commented on README.md
> + This annotation can only be used for character like ABAP types, i.e., types that are mapped to JSON type `string`.
```suggestion
 This annotation can only be used for characters like ABAP types, i.e., types that are mapped to JSON type `string`.
```

2023-03-27 07:08 UTC, albertmink commented on README.md
> + The encoding used to store the content of a string field can be specifed with the annotation
```suggestion
 The encoding used to store the content of a string field can be specified with the annotation
```

2023-03-27 07:08 UTC, albertmink commented on README.md
> + This annotation can also only be used for character like ABAP types, i.e., types that are mapped to JSON type `string`.
```suggestion
 This annotation can also only be used for characters like ABAP types, i.e., types that are mapped to JSON type `string`.
```

2023-03-27 07:14 UTC, wurzka commented
Thanks @albertmink !

2023-03-27 07:52 UTC, albertmink reviewed
Introducing features that are not (yet?) relevant for ABAP file formats here is a potential risk, right? Considering there is not much of guidance/explanation for the intended usage and its prominent appearance on the readme.

---
Let's keep this in mind and observe it carefully. Approving and moving on 🚂

2023-03-27 07:53 UTC, albertmink approved these changes

2023-03-30 12:50 UTC, merged

2023-03-30 12:51 UTC, schneidermic0 commented
@wurzk, @larshp and I have just decided in a call to merge the changes for now.