Do inplace de-/serialization
SAP/abap-file-formats-tools pull request #43
Opened 2022-04-07 13:41 UTC by albertmink

fixes #36

2022-04-07 14:34 UTC, wurzka requested changes
See my comment :)

2022-04-07 14:34 UTC, wurzka commented on src/zcl_aff_writer_xslt.clas.testclasses.abap
> -    cl_aff_content_handler_factory=>get_handler_for_plain_text( )->deserialize(
The cl_aff_content_handler_factory is also called in an other place of this class. So it should be removed there, too.

2022-04-08 08:31 UTC, wurzka approved these changes
LGTM :) But as there are more calls of the aff-framework, maybe we should not say that it fixes the linked issue. Or what do you think?

2022-04-08 08:36 UTC, albertmink commented
follow up item is #45. Ok @wurzka ?

2022-04-08 08:45 UTC, merged